minimumReleaseAge: 7200
preferFrozenLockfile: true
blockExoticSubdeps: true

# This will be useful in the future
# But exclusions have to be speific versions
# So that will break renovate?
# rendering it a  trade off.
# Add it if and when no packages need exclusions?
# Testing for now...
#trustPolicy: no-downgrade
#trustPolicyExclude:
#  - chokidar@4.0.3
#  - semver@6.3.1
#  - vite@6.4.1

allowBuilds:
  esbuild: false
  sharp: false
  workerd: false

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd
